"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { developmentUsers } from "./development-users";
import styles from "./page.module.css";

const pageSize = 8;
const displayDate = (date) => new Intl.DateTimeFormat("en-US", { month: "short", day: "2-digit", year: "numeric" }).format(new Date(`${date}T00:00:00`));
const titleCase = (value) => value.charAt(0).toUpperCase() + value.slice(1);

export default function AdminUsersPage() {
  const [draft, setDraft] = useState(""); const [search, setSearch] = useState(""); const [showFilters, setShowFilters] = useState(false);
  const [role, setRole] = useState("all"); const [status, setStatus] = useState("all"); const [sort, setSort] = useState("joined"); const [modal, setModal] = useState("");
  const users = useMemo(() => developmentUsers.filter((user) => {
    const value = search.toLowerCase(); return (!value || `${user.id} ${user.name} ${user.email}`.toLowerCase().includes(value)) && (role === "all" || user.role === role) && (status === "all" || user.status === status);
  }).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : new Date(b.joined) - new Date(a.joined)), [search, role, status, sort]);
  const clearFilters = () => { setDraft(""); setSearch(""); setRole("all"); setStatus("all"); setSort("joined"); };
  const performSearch = (event) => { event?.preventDefault(); setSearch(draft); };
  return <section className={styles.usersPage}>
    <form className={styles.toolbar} onSubmit={performSearch}><div className={styles.searchField}><span aria-hidden="true">⌕</span><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Search by name, email, or ID..." /></div><button className={styles.primaryButton} type="submit">Search</button><button className={styles.filterButton} type="button" onClick={() => setShowFilters((open) => !open)}>☷&nbsp; Filter &amp; Sort</button><Link className={styles.primaryButton} href="/admin/users/pending-verifications">♧&nbsp; Pending Users</Link><button className={styles.primaryButton} type="button" onClick={() => setModal("add")}>＋ Add User</button></form>
    {showFilters && <div className={styles.filters}><label>Role<select value={role} onChange={(event) => setRole(event.target.value)}><option value="all">All</option><option value="pet_owner">Pet Owner</option><option value="sitter">Sitter</option></select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All</option><option value="active">Active</option><option value="pending">Pending</option><option value="suspended">Suspended</option></select></label><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="joined">Joined date</option><option value="name">Name</option></select></label><button type="button" onClick={clearFilters}>Clear filters</button></div>}
    <article className={styles.tableCard}><div className={styles.tableWrap}><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Joined<br />date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.slice(0, pageSize).map((user) => <tr key={user.id}><td><div className={styles.person}><span className={styles.avatar}>{user.name.split(" ").map((part) => part[0]).join("")}</span><strong>{user.name}</strong></div></td><td>{user.email}</td><td><span className={`${styles.role} ${styles[user.role]}`}>{user.role === "sitter" ? "Sitter" : "Pet Owner"}</span></td><td>{displayDate(user.joined)}</td><td><span className={`${styles.status} ${styles[user.status]}`}><i />{titleCase(user.status)}</span></td><td><div className={styles.actions}><button type="button" aria-label={`Edit ${user.name}`} title="Edit unavailable until a Users API is connected" disabled>✎</button><button type="button" aria-label={`Delete ${user.name}`} title="Delete user" onClick={() => setModal(`delete:${user.name}`)}>▥</button><button type="button" aria-label={`Suspend ${user.name}`} title="Suspend user" onClick={() => setModal(`suspend:${user.name}`)}>⊘</button></div></td></tr>)}</tbody></table>{!users.length && <div className={styles.emptyState}><strong>No users found</strong><span>Try changing your search or filters.</span><button type="button" onClick={clearFilters}>Clear filters</button></div>}</div><footer className={styles.pagination}><span>Showing {users.length ? "1" : "0"}–{Math.min(users.length, pageSize)} of {users.length} users</span><div><button type="button" disabled aria-label="Previous page">‹</button><button type="button" className={styles.current} aria-current="page">1</button><button type="button" disabled>2</button><button type="button" disabled>3</button><em>…</em><button type="button" disabled aria-label="Next page">›</button></div></footer></article>
    {modal && <div className={styles.modalBackdrop} role="presentation"><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">{modal === "add" ? "Add user" : "Confirm action"}</h2><p>{modal === "add" ? "A user-creation flow is not connected yet." : `${modal.split(":")[0] === "delete" ? "Delete" : "Suspend"} ${modal.split(":")[1]}? This is a UI placeholder and will not change any data.`}</p><div><button type="button" onClick={() => setModal("")}>Cancel</button><button type="button" onClick={() => setModal("")}>{modal === "add" ? "Close" : "I understand"}</button></div></section></div>}
  </section>;
}
