"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { developmentAds } from "./development-ads";
import styles from "./page.module.css";

const tabs = [["all", "All"], ["active", "Active"], ["pending", "Pending Approval"], ["expired", "Expired/Removed"]];
const displayStatus = (status) => status === "pending" ? "Pending Approval" : status.charAt(0).toUpperCase() + status.slice(1);

export default function AdminPetMarketplacePage() {
  const [tab, setTab] = useState("all"); const [modal, setModal] = useState(null);
  const ads = useMemo(() => developmentAds.filter((ad) => tab === "all" || (tab === "expired" ? ["expired", "removed"].includes(ad.status) : ad.status === tab)), [tab]);
  return <section className={styles.page}><header className={styles.header}><h1>Posted Ads</h1><Link href="/admin/marketplace/pending" className={styles.pendingLink}>＋ Pending Ads</Link></header><div className={styles.tabs} role="tablist" aria-label="Advertisement status">{tabs.map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} className={tab === value ? styles.activeTab : undefined} onClick={() => setTab(value)}>{label}</button>)}</div><div className={styles.adList}>{ads.map((ad) => <article className={styles.adCard} key={ad.id}><button className={styles.cardDetails} type="button" aria-label={`View ${ad.title} details`} onClick={() => setModal({ type: "details", ad })}><span className={styles.imageWrap}><img src={ad.image} alt="" /></span><span className={styles.content}><strong>{ad.title}</strong><span className={styles.description}>{ad.description}</span><span className={styles.meta}>◉ {ad.views} views <i /> {ad.dateLabel}</span></span></button><span className={`${styles.status} ${styles[ad.status]}`}>{ad.status === "active" && <i />} {displayStatus(ad.status)}</span><div className={styles.actions}><button type="button" aria-label={`Edit ${ad.title}`} title="Edit development advertisement" onClick={() => setModal({ type: "edit", ad })}>✎</button><button type="button" aria-label={`Delete ${ad.title}`} title="Delete advertisement" onClick={() => setModal({ type: "delete", ad })}>▥</button></div></article>)}{!ads.length && <div className={styles.empty}><strong>No advertisements found</strong><span>There are no advertisements in this category.</span><button type="button" onClick={() => setTab("all")}>Show all ads</button></div>}</div>{modal && <div className={styles.modalBackdrop}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="ad-modal-title"><h2 id="ad-modal-title">{modal.type === "details" ? modal.ad.title : modal.type === "edit" ? "Edit advertisement" : "Delete advertisement?"}</h2><p>{modal.type === "details" ? `${modal.ad.description} ${modal.ad.views} views · ${modal.ad.dateLabel}.` : modal.type === "edit" ? "Editing is available as a UI preview only until an advertisements API is connected." : "This action is a UI placeholder. A backend delete endpoint is required before an advertisement can be removed."}</p><button type="button" onClick={() => setModal(null)}>Close</button></section></div>}</section>;
}
